# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
# (Required) Acceptable Values: Component, Resource, System
# A repo will almost certainly be a Component.
kind: Component
metadata:
  name: 'training-courses'
  description: "Open edX Training Courses (tar gz archives)"
  links:
    - url: "https://open-edx-proposals.readthedocs.io/en/latest/index.html"
      title: "OEP Index"
      # Backstage uses the MaterialUI Icon Set.
      # https://mui.com/material-ui/material-icons/
      # The value will be the name of the icon.
      icon: "Web"
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: "sarina"
spec:

  # (Required) This can be a group (`group:<github_group_name>`) or a user (`user:<github_username>`).
  # Don't forget the "user:" or "group:" prefix. Groups must be GitHub team
  # names in the openedx GitHub organization: https://github.com/orgs/openedx/teams
  #
  # If you need a new team created, create an issue with tCRIL engineering:
  # https://github.com/openedx/tcril-engineering/issues/new/choose
  owner: user:sarina

  # (Required) Acceptable Type Values: service, website, library
  type: 'website'

  # (Required) Acceptable Lifecycle Values: experimental, production, deprecated
  lifecycle: 'production'
